---
regions:
  - eu-west-2

account-blocklist:
  - "999999999999"  # We need something in the blocklist, or nuke won't run

accounts:
  "761688265120":  # finos-cfi tenancy
    filters:
      IAMUser:
        - "csc-eks"
      IAMUserPolicyAttachment:
        - "csc-eks -> AdministratorAccess"
      IAMUserAccessKey:
        - "csc-eks -> AKIA3CWBISGQO7E5BFYA"

resource-types:  # only nuke these resources
  targets:
    - EC2RouteTable
    - EC2Subnet
    - EC2NetworkInterface
    - EC2DHCPOption
    - EC2RouteTable
    - EC2NATGateway
    - EC2SecurityGroup
    - AutoScalingGroup
    - EC2VPC
    - EC2Instance
    - EC2InternetGatewayAttachment
    - EC2Address
    - EC2Volume
    - LaunchConfiguration
    - EKSCluster
